version: "3.8"

services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: square_pipeline
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - ./data:/app/data
      - ./we-service-account.json:/app/we-service-account.json
      - ${HOME}/.dbt:/app/.dbt # Mount host dbt profiles
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/we-service-account.json
      - BIGQUERY_DATASET=Sales_Test
      - BIGQUERY_PROJECT_ID=we-analysis
      - DBT_PROFILES_DIR=/app/.dbt
    command: bash
    restart: always
    networks:
      - square_pipeline_network

networks:
  square_pipeline_network:
    driver: bridge
