version: 2

models:
  - name: dim_items
    description: Dimension table for unique menu items and their modifiers
    columns:
      - name: item_id
        description: Primary key for individual menu items
        tests:
          - unique
          - not_null
      - name: item_name
        description: Name of the menu item
        tests:
          - not_null
      - name: modifier_name
        description: Customization or modifier applied to the item

  - name: dim_orders
    description: Dimension table for order status information
    columns:
      - name: order_id
        description: Primary key for orders
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('dev_order_payments')
              field: order_id
      - name: order_state
        description: Current state of the order (e.g., open, closed, canceled)

  - name: dim_payments
    description: Dimension table for payment transaction details
    columns:
      - name: transaction_id
        description: Primary key for payment transactions
        tests:
          - unique
          - not_null
      - name: transaction_state
        description: Status of the payment transaction
        tests:
          - not_null
      - name: transaction_source
        description: Source of the payment (e.g., online, in-store)
      - name: transaction_method
        description: Payment method used (e.g., credit card, cash)

  - name: dim_time
    description: Time dimension table for granular timestamp analysis
    columns:
      - name: date_time_key
        description: Surrogate key in YYYYMMDDHHMMSS format
        tests:
          - unique
          - not_null
      - name: timestamp_utc
        description: Original UTC timestamp
        tests:
          - not_null
      - name: day_name
        description: Full name of the weekday
        tests:
          - accepted_values:
              values:
                [
                  "Sunday",
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ]
      - name: is_weekend
        description: Flag indicating weekend days (Saturday/Sunday)
        tests:
          - accepted_values:
              values: [true, false]
      # Add tests for other columns (year, month, etc) similarly

  - name: fact_sales
    description: Fact table containing sales transaction details
    columns:
      - name: transaction_id
        description: Foreign key to payment dimension
        tests:
          - relationships:
              to: ref('dev_order_payments'
              field: transaction_id
      - name: order_id
        description: Foreign key to order dimension
        tests:
          - relationships:
              to: ref('dev_order_payments'
              field: order_id
      - name: line_item_id
        description: Foreign key to items dimension
        tests:
          - relationships:
              to: ref('dev_order_items'
              field: item_id
      - name: date_time_key
        description: Foreign key to time dimension
        tests:
          - relationships:
              to: ref('dev_order_items'
              field: date_time_key
      - name: item_quantity
        description: Quantity of items sold
        tests:
          - not_null
          - positive_value:
              severity: warn
      - name: item_gross_amt
        description: Gross amount before taxes and modifiers
        tests:
          - not_null
      - name: payment_total
        description: Total amount paid including taxes and tips
        tests:
          - not_null
