version: 2

models:
  - name: fact_sales
    description: "Aggregated sales data at the order level."
    columns:
      - name: order_date
        description: "The date of the order."
        tests:
          - not_null
      - name: total_sales
        description: "Total sales for the given date."
        tests:
          - not_null
      - name: total_gross_sales
        description: "Gross sales for the given date."
        tests:
          - not_null
      - name: total_orders
        description: "Number of completed orders on the given date."
      - name: total_payments
        description: "Number of completed payments on the given date."

  - name: fact_order_items
    description: "Detailed item-level sales data."
    columns:
      - name: order_id
        description: "Unique identifier for the order."
        tests:
          - not_null
      - name: item_id
        description: "Unique identifier for the line item."
        tests:
          - not_null
      - name: item_name
        description: "Name of the purchased item."
      - name: quantity
        description: "Number of items sold."
      - name: revenue
        description: "Revenue generated by the item."

  - name: dim_items
    description: "Item dimension containing attributes of items sold."
    columns:
      - name: item_id
        description: "Unique identifier for the line item."
        tests:
          - unique
          - not_null
      - name: item_name
        description: "Name of the purchased item."
      - name: modifier_name
        description: "Modifier name associated with the item."
      - name: modifier_price
        description: "Modifier price applied to the item."

  - name: dim_time
    description: "Time dimension with dates and related attributes."
    columns:
      - name: date
        description: "Unique date."
        tests:
          - unique
          - not_null
      - name: day
        description: "Day of the month."
      - name: month
        description: "Month of the year."
      - name: year
        description: "Year."
      - name: day_of_week
        description: "Day of the week."

  - name: dim_orders
    description: "Order dimension with payment data."
    columns:
      - name: order_id
        description: "Unique identifier for the order."
        tests:
          - unique
          - not_null
      - name: payment_id
        description: "Unique identifier for the payment."
      - name: payment_amount
        description: "Amount of the payment."
      - name: payment_status
        description: "Status of the payment."
      - name: payment_source
        description: "Source of the payment (e.g., CARD, CASH)."
  - name: dim_payments
    description: "Order dimension with payment data."
    columns:
      - name: payment_id
        description: "Unique identifier for the payment."
        tests:
          - unique
          - not_null
      - name: payment_status
        description: "Status of the payment."
      - name: payment_source
        description: "Source of the payment (e.g., CARD, CASH)."
