version: 2

models:
  - name: dev_order_payments
    description: >
      This view aggregates payment data with related order and line item details.
      It joins the staging tables: stg_payments, stg_orders, and stg_line_items.
    columns:
      - name: payment_id
        description: "Unique identifier for each payment."
        tests:
          - not_null
          - unique
      - name: order_id
        description: "Identifier for the order, serving as a foreign key."
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: line_item_id
        description: "Identifier for the line item associated with the payment."
        tests:
          - not_null
          - relationships:
              to: ref('stg_line_items')
              field: line_item_id
      - name: payment_timestamp
        description: "Timestamp when the payment was made."
        tests:
          - not_null
      - name: payment_status
        description: "Status of the payment (e.g., SUCCESS, FAILED)."
        tests:
          - not_null
      - name: payment_source
        description: "Source through which the payment was initiated (e.g., POS, online)."
      - name: payment_amount
        description: "The order amount as recorded in the payment data."
      - name: total_collected_amount
        description: "Total amount collected from the payment."
      - name: payment_approved_amount
        description: "Amount approved for the payment."
      - name: payment_tip_amount
        description: "Tip amount included in the payment."
      - name: payment_processing_fee
        description: "Fee charged for processing the payment."
      - name: payment_receipt_url
        description: "URL to access the payment receipt."
      - name: application_detail
        description: >
          Detail about the payment source.
          Expected values: 'SQUARE_POS' (in-store), 'ECOMMERCE_API' (online), 'OTHER' (gift card).
        tests:
          - accepted_values:
              values: ["SQUARE_POS", "ECOMMERCE_API", "OTHER"]
      - name: order_timestamp
        description: "Timestamp when the order was placed."
      - name: order_state
        description: "Current state of the order."
      - name: order_amount
        description: "Total amount for the order as recorded in the order data."
      - name: order_tax
        description: "Tax applied to the order."
      - name: order_tip
        description: "Tip applied to the order."
      - name: order_discount
        description: "Discount applied to the order."
      - name: item_base_price
        description: "Base price of the line item."
      - name: item_gross_amount
        description: "Gross sales amount for the line item."
      - name: item_total_amount
        description: "Total amount for the line item."
      - name: modifier_price
        description: "Price charged for any modifiers on the line item."

  - name: dev_order_items
    description: >
      This view provides order details combined with associated line item information.
      It joins the staging orders and line items tables.
    columns:
      - name: order_id
        description: "Unique identifier for each order."
        tests:
          - not_null
          - unique
      - name: order_timestamp
        description: "Timestamp when the order was placed."
        tests:
          - not_null
      - name: line_item_id
        description: "Unique identifier for each line item associated with an order."
        tests:
          - not_null
      - name: item_name
        description: "Name of the item ordered."
        tests:
          - not_null
      - name: item_quantity
        description: "Quantity of the item ordered. Must be greater than 0."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "item_quantity > 0"
      - name: modifier_name
        description: "Name of the modifier applied to the item, if any."
