version: 2

models:
  - name: stg_payments
    description: "Cleaned and normalized payments data."
    columns:
      - name: payment_id
        description: "Unique identifier for the payment."
      - name: payment_created_at
        description: "Timestamp when the payment was created."
      - name: amount
        description: "Payment amount in USD."
      - name: status
        description: "Status of the payment (e.g., COMPLETED)."
      - name: order_id
        description: "Unique identifier for the related order."

  - name: stg_orders
    description: "Cleaned and normalized orders data."
    columns:
      - name: order_id
        description: "Unique identifier for the order."
      - name: location_id
        description: "Identifier for the location where the order was placed."
      - name: total_amount
        description: "Total amount for the order in USD."
      - name: order_created_at
        description: "Timestamp when the order was created."

  - name: stg_line_items
    description: "Cleaned and normalized line items data."
    columns:
      - name: order_id
        description: "Unique identifier for the order this item belongs to."
      - name: item_name
        description: "Name of the purchased item."
      - name: quantity
        description: "Quantity of the item purchased."
      - name: gross_sales
        description: "Gross sales amount for the line item."
