version: 2

sources:
  - name: raw
    description: "Raw extracted data from the Square API."
    database: "{{ env_var('BIGQUERY_PROJECT_ID') }}"
    schema: "{{ env_var('BIGQUERY_DATASET') }}"
    tables:
      - name: payments
        description: "Raw payments data extracted from Square API."
        columns:
          - name: id
            description: "Unique identifier for the payment."
          - name: created_at
            description: "Timestamp when the payment was created."
          - name: amount_money
            description: "Payment amount and currency."
          - name: status
            description: "Status of the payment (e.g., COMPLETED)."
      - name: orders
        description: "Raw orders data extracted from Square API."
        columns:
          - name: order_id
            description: "Unique identifier for the order."
          - name: total_money
            description: "Total amount for the order."
          - name: created_at
            description: "Timestamp when the order was created."
      - name: line_items
        description: "Raw line items data extracted from Square API."
        columns:
          - name: order_id
            description: "Unique identifier for the order this item belongs to."
          - name: item_name
            description: "Name of the purchased item."
          - name: quantity
            description: "Quantity of the item purchased."
          - name: gross_sales
            description: "Gross sales amount for the line item."
